<a href="https://colab.research.google.com/github/GOVINDFROMINDIA/R-Basics/blob/main/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
M <- matrix(c(1:16), nrow = 4, byrow = TRUE)
print(M)

# Elements are arranged sequentially by column.
N <- matrix(c(1:16), nrow = 4, byrow = FALSE)
print(N)

print(M[1,3])
print(M[4,])
print(N[,3])

# Add the matrices.
result <- M +N
cat("Result of addition","\n")
print(result)

# Subtract the matrices
result <- M - N
cat("Result of subtraction","\n")
print(result)

# Multiply the matrices.
result <- M * N
cat("Result of multiplication","\n")
print(result)

# Divide the matrices
result <- M /N
cat("Result of division","\n")
print(result)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12
[4,]   13   14   15   16
     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16
[1] 3
[1] 13 14 15 16
[1]  9 10 11 12
Result of addition 
     [,1] [,2] [,3] [,4]
[1,]    2    7   12   17
[2,]    7   12   17   22
[3,]   12   17   22   27
[4,]   17   22   27   32
Result of subtraction 
     [,1] [,2] [,3] [,4]
[1,]    0   -3   -6   -9
[2,]    3    0   -3   -6
[3,]    6    3    0   -3
[4,]    9    6    3    0
Result of multiplication 
     [,1] [,2] [,3] [,4]
[1,]    1   10   27   52
[2,]   10   36   70  112
[3,]   27   70  121  180
[4,]   52  112  180  256
Result of division 
     [,1]     [,2]      [,3]      [,4]
[1,] 1.00 0.400000 0.3333333 0.3076923
[2,] 2.50 1.000000 0.7000000 0.5714286
[3,] 3.00 1.428571 1.0000000 0.8000000
[4,] 3.25 1.750000 1.2500000 1.0000000
